---
# defaults file for minikube
# code: language=ansible

# Minikube version number
minikube_version: '1.31.2' 

# Directory to store files downloaded for Minikube
minikube_download_dir: "{{ x_ansible_download_dir | default(ansible_facts.env.HOME + '/.ansible/tmp/downloads') }}"