---
- hosts: localhost
  collections:
    - homezone.desktop
  roles:
    - role: community
    - role: minikube
  vars:
    community_dir: "~/Community"
    community_bin_dir: "{{ community_dir }}/bin"
    minikube_install_dir: "{{ community_bin_dir }}"
    minikube_version: '1.31.2'   

